### ISSUE TITLE
Dark Pastel in VS Studio 2019

### ISSUE THREAD

**Issue by Rascalnicough** [migliori/vsc-dark-pastel-theme#1]
*To be clear, there is no issue with this theme in VS Code.*

I really love this theme in VS Code -- it's very pleasing while also being easy for me to read and understand. However, I have recently been forced to migrate to VS Studio 2019, where colors and themes are awful and a huge pain to try to tweak.

Is there a version of the Dark Pastel theme for VS Studio 2019 or a quick way to export the VS Code theme's color settings to VS Studio 2019?

**Comment by migliori** [comment]
Hi Rascalnicough,

There's no version for VS Studio 2019. You may try to go to the _output_ tab in the command panel, then choose _extensions_ in the dropdown list and see if there's any message about the theme.

Sorry I can't help more
